<?php

namespace App\Http\Controllers\Admin;

use App\Contact;
use App\Notifications\ContactReply;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use TCG\Voyager\Events\BreadDataUpdated;
use TCG\Voyager\Http\Controllers\VoyagerBaseController;

class ContactsController extends VoyagerBaseController
{
    public function show(Request $request, $id)
    {
        // update message as `read` when viewed
        $contact = Contact::find($id);
        if($this->authorize('read', $contact))
            $contact->update(['read' => true]);

        return parent::show($request, $id); // TODO: Change the autogenerated stub
    }
    public function edit(Request $request, $id)
    {
        $contact = Contact::find($id);
        if($this->authorize('read', $contact))
            $contact->update(['read' => true]);
        return parent::edit($request, $id); // TODO: Change the autogenerated stub
    }

    public function reply(Request $request, $id)
    {
        $id = $id instanceof Model ? $id->{$id->getKeyName()} : $id;
        $contact = Contact::find($id);
        // Check permission
        $this->authorize('edit', $contact);
        // Compatibility with Model binding.
        $slug = $this->getSlug($request);

        $dataType = \Voyager::model('DataType')->where('slug', '=', 'contacts')->first();

        // Validate fields with ajax
        $val = $this->validateBread($request->all(), $dataType->editRows, $dataType->name, $id)->validate();

        $contact->reply = $request->reply;
        if($request->read)
            $contact->read = true;
        else
            $contact->read = false;
        $contact->save();

        // send mail to contact
        if($request->send)
            auth()->user()->notify(new ContactReply($contact));

        event(new BreadDataUpdated($dataType, $contact));

        return redirect()
            ->route("voyager.{$dataType->slug}.index")
            ->with([
                'message'    => __('voyager::generic.successfully_updated')." {$dataType->display_name_singular}",
                'alert-type' => 'success',
            ]);

    }
}
